name: "Test and verify Terraform code"
description: "Combining all terraform test actions into one"

inputs:
  environment:
    type: string
    required: true
  region:
    type: string
    required: true
  iam-role:
    type: string
    required: true

runs:
  using: "composite"
  
  steps:
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform Validate
      run: terraform validate
      shell: bash
      working-directory: infra
    - name: Terraform fmt
      run: terraform fmt -check
      shell: bash
      working-directory: infra
      continue-on-error: false
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
    - name: Terraform lint
      run: tflint -f compact
      shell: bash
      working-directory: infra
